// <auto-generated />
namespace MvcSegundoExemplo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSobreNome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSobreNome));
        
        string IMigrationMetadata.Id
        {
            get { return "201301170126522_AddSobreNome"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
